name: publication_regulation_cancer_asprograms
channels:
    - conda-forge
    - bioconda
    - pytorch
    - r
dependencies:
    - snakemake=7.32.4
    - pip
    - pytorch
    - lightning
    - torchmetrics
    - pandas
    - numpy
    - joblib
    - scikit-learn
    - statsmodels
    - tqdm
    - networkx
    - scipy
    - scanpy
    - r-base=4.1
    - r-optparse
    - r-tidyverse
    - r-ggpubr
    - r-cowplot
    - r-extrafont
    - r-ggrepel
    - r-ggplotify
    - r-ggvenn
    - r-scattermore
    - r-proc
    - r-ggraph
    - r-tidygraph
    - bioconductor-viper
    - bioconductor-clusterprofiler
    - bioconductor-complexheatmap
    - bioconductor-biocparallel
